package:
  name: pygit2
  version: 0.22.1

source:
  git_url: https://github.com/libgit2/pygit2
  git_tag: v0.22.1

build:
  number: 3

requirements:
  build:
    - system # [linux]
    - python
    - libgit2
    - cffi >=0.8.1
    - pkgconfig # [linux]
  run:
    - system # [linux]
    - python
    - libgit2
    - cffi >=0.8.1

about:
  home: http://www.pygit2.org/
  license: GPLv2 with a special Linking Exception
  summary: 'Pygit2 is a set of Python bindings to the libgit2 shared library, libgit2 implements the core of Git.'
