package:
  name: qt5
  version: 5.5.1

source:
  fn:   qt-everywhere-opensource-src-5.5.1.tar.gz
  url:  http://download.qt.io/official_releases/qt/5.5/5.5.1/single/qt-everywhere-opensource-src-5.5.1.tar.gz
  md5:  59f0216819152b77536cf660b015d784

build:
  number: 3

requirements:
  build:
    - zlib
    - libpng        1.6*
    - jpeg
    - icu           56.1 0
    - patch                  [win]
    - python                 [win]
    - jom                    [win]
    - openssl                [unix]
    - freetype               [unix]
    - fontconfig             [linux]
    # also needed on [linux]: apt-get install flex bison gperf libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxkbcommon-dev libxkbcommon-x11-dev

  run:
    - zlib
    - libpng        1.6*
    - jpeg
    - icu           56.1 0
    - openssl                [unix]
    - freetype               [unix]
    - fontconfig             [linux]

about:
  home: http://www.qt.io
  license: LGPL
