package:
  name: openocd
  version: 0.10.0.git

source:
  git_tag: master
  git_url: git://github.com/ntfreak/openocd

build:
  number: 0

requirements:
  build:
    - system # [linux]
    - libftdi
  run:
    - libftdi

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
