package:
  name: openocd
  version: 0.10.0.git

source:
  git_tag: master
  git_url: https://github.com/ntfreak/openocd

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - system # [linux]
    - libusb >=1.0.16
  run:
    - libusb >=1.0.16

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
