package:
  name: rust-core-or1k
  version: "1.12.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq

build:
  number: 2

requirements:
  build:
    - rustc 1.12.0 2
    - llvm-or1k 3.8.1 15 # >=15, but inexpressible in conda
  run:
    - rustc 1.12.0 2

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
