package:
  name: rust-core-or1k
  version: "1.14.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq-1.14.0

build:
  number: 11

requirements:
  build:
    - rustc 1.14.0 9
  run:
    - rustc 1.14.0 9

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
