package:
  name: sphinxcontrib-wavedrom
  version: "1.1.0"

source:
  fn: sphinxcontrib-wavedrom-1.1.0.zip
  url: https://pypi.python.org/packages/42/a1/4d97624b39e3056304979bed8ec59508ad99714f726cdddba1001446439e/sphinxcontrib-wavedrom-1.1.0.zip
  md5: 4c40d24b4a3e6db19a33fe218ae1a116

build:
  noarch_python: True
  # preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=0.6

  run:
    - python
    - sphinx >=0.6

test:
  imports:
    - sphinxcontrib.wavedrom

about:
  home: https://github.com/bavovanachte/sphinx-wavedrom
  license: MIT license
  summary: 'A sphinx extension that allows generating wavedrom diagrams based on their textual representation'
