package:
  name: libssh2
  version: 1.7.0.git

source:
  git_url: https://github.com/libssh2/libssh2
  git_tag: 7934c9ce2a029c43e3642a492d3b9e494d1542be

build:
  number: 2

requirements:
  build:
    - system # [linux]
    - cmake

about:
  home: http://www.libssh2.org/
  license: BSD
  summary: 'libssh2 is a client-side C library implementing the SSH2 protocol'
