package:
  name: libssh2
  version: 1.6.0

source:
  git_url: https://github.com/libssh2/libssh2
  git_tag: libssh2-1.6.0

build:
  number: 3

requirements:
  build:
    - system # [linux]
    - cmake # [linux]
    - openssl
  run:
    - openssl

about:
  home: http://www.libssh2.org/
  license: BSD
  summary: 'libssh2 is a client-side C library implementing the SSH2 protocol'
