package:
  name: llvm-or1k
  version: "3.8.1"

source:
  git_url: https://github.com/openrisc/llvm-or1k
  git_tag: master

build:
  number: 9

requirements:
  build:
    - system [linux]
    - cmake [linux]
  run:
    - system [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.8.1/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
