package:
  name: libusb
  version: 1.3

source:
  fn:   libusb-1.0.20.tar.bz2
  url:  https://github.com/libusb/libusb/releases/download/v1.0.20/libusb-1.0.20.tar.bz2
  sha1: 9537243f165927bde74ad742e6b3effb0bd50cd2

build:
  number: 0

requirements:
  build:
    - system # [linux]

about:
  home: http://libusb.org
  license: LGPLv2.1
  summary: 'A cross-platform library to access USB devices'
